"""added timestamps to user model

Revision ID: 3641efc36b10
Revises: a8f680a56863
Create Date: 2020-10-19 11:22:29.940794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3641efc36b10'
down_revision = 'a8f680a56863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
