"""added timestamps to user model

Revision ID: 686ce9484ff5
Revises: 3641efc36b10
Create Date: 2020-10-19 11:31:27.488411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686ce9484ff5'
down_revision = '3641efc36b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
